import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { gql, useQuery } from '@apollo/client';

const GET_EMOJIS = gql`
  query {
    emojis {
      chars
      id
      name
      unicode
    }
  }
`;
const Home: NextPage = () => {
  const { loading, data, error } = useQuery(GET_EMOJIS);

  if (error) return <div>Error in the query {error.message}</div>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Backend de la suerte</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href={`data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>👑</text></svg>`}
        ></link>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>¡Hola malandriner! Aquí tienes tu oro:</h1>
        <h2 className={styles.emoji}>
          {loading ? 'Loading...' : data.emojis[0].chars}
        </h2>
      </main>
    </div>
  );
};

export default Home;
